### ISSUE TITLE
Add a `registries.conf` file

### ISSUE THREAD

**Issue by sillypoise** [sillypoise/sp-dotfiles#1]
For podman to work we need to define some default registries.

Excellent! You're really getting to the core of how Podman and the broader containers ecosystem works — and yes, you're absolutely right to want to understand what each of these configuration files does.

Here's a breakdown of the **three most important config files** used by **Podman**, **Buildah**, **Skopeo**, and other `containers/*` tools:

---

### **Purpose**:

Specifies *which container registries* to use when pulling images, and how to treat them (secure, blocked, etc.).

### **Used by**:

* Podman
* Buildah
* Skopeo
* CRI-O

### **Key Sections**:

```ini
[registries.search]
registries = ['docker.io', 'quay.io']

[registries.insecure]
registries = ['my.local.registry:5000']

[registries.block]
registries = ['some-bad-registry.io']
```

### **Analogy**:

Think of this like your browser’s DNS resolver settings + blacklist.

---

### **Purpose**:

Controls **image signature verification and trust policies** — i.e., when pulling images, should we verify their cryptographic signatures? And from which registries?

### **Used by**:

* Podman
* Skopeo
* Buildah
* Containers/image library

### **Default content (if you don't need signature validation)**:

```json
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ]
}
```

This means: "Don’t check signatures, just trust any image."

### **Analogy**:

Think of this like your browser’s SSL/TLS certificate policy — do you trust this site?

---

### **Purpose**:

Defines **runtime defaults** for containers:

* Default CPU/memory limits
* Default runtime (crun vs runc)
* Networking mode (e.g. `bridge`, `slirp4netns`)
* Default image volume handling
* Timeouts, etc.

### **Used by**:

* Podman

### Example (minimal):

```toml
[engine]
cgroup_manager = "systemd"
events_logger = "journald"
```

Other options you might set include:

```toml
network_cmd_path = "/usr/bin/netavark"
volume_path = "/my/custom/volume/path"
```

### **Analogy**:

Like `.npmrc` or `.gitconfig` — this defines how Podman should behave by default.

---

## ✅ Where to Place These

You can define them:

| Scope             | Path                        |
| ----------------- | --------------------------- |
| **System-wide**   | `/etc/containers/`          |
| **User-specific** | `$HOME/.config/containers/` |

User configs **override** system configs.

---

## 🔧 In Your Case (Nix Install)

You’ll need to create at least:

### ✅ `~/.config/containers/policy.json` (to fix your current error)

```bash
mkdir -p ~/.config/containers
nano ~/.config/containers/policy.json
```

Paste this:

```json
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ]
}
```

Then try again:

```bash
podman pull nginx
```

---

## 🧠 Summary

| File              | Purpose                                    | Required for basic use?                        |
| ----------------- | ------------------------------------------ | ---------------------------------------------- |
| `registries.conf` | Where to pull images from                  | ✅ Yes                                          |
| `policy.json`     | How to trust/signature-verify images       | ✅ Yes (at least a default)                     |
| `containers.conf` | Container runtime defaults (cgroups, etc.) | ❌ Optional unless customizing runtime behavior |

---

Would you like a minimal example setup (with all three) you can copy into your config directory or declare in Nix?

**Comment by sillypoise** [comment]
Absolutely — let’s answer your first follow-up and then set you up with solid default configs.

---

### 🔐 **2. Do I need a signature for pulling from Docker Hub?**

**No, you do not.**

Docker Hub images typically **do not come with cryptographic signatures** unless you're using a specific solution like:

* **Docker Content Trust** (old)
* **Sigstore/Cosign** (modern)
* **Red Hat-signed images** from trusted registries like `registry.access.redhat.com` or `quay.io/redhat/…`

By default, Podman doesn't enforce signature verification unless you configure it — so just adding the `"insecureAcceptAnything"` policy is safe for most general use cases (like pulling `nginx`, `alpine`, `node`, etc.).

---

### ✅ Set You Up with Good Defaults

Let’s go ahead and create both:

---

## 🧾 `~/.config/containers/policy.json`

### 🔒 Purpose: Signature verification policy

### 🔧 Recommended default:

```json
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ]
}
```

This will let Podman pull images from Docker Hub and elsewhere without requiring signed images — a common setup for development or general use.

---

## 🧾 `~/.config/containers/containers.conf`

### ⚙️ Purpose: Default runtime behaviour for Podman

Create the file:

```bash
mkdir -p ~/.config/containers
nano ~/.config/containers/containers.conf
```

Paste the following minimal, stable defaults:

```toml
[containers]
# Where volumes are stored
volume_path = "/home/sillypoise/.local/share/containers/storage/volumes"

# Image volumes: "bind", "ignore", or "copy"
image_volumes = "bind"

[engine]
# Logging system (journald is clean on Arch)
events_logger = "journald"

# Cgroup manager — systemd works with most Arch setups
cgroup_manager = "systemd"

# Network backend: netavark is the default with rootless Podman
network_backend = "netavark"

# Optional: explicitly set OCI runtime (likely already inferred)
runtime = "crun"
```

> You can omit or change `volume_path` if you're happy with the current setup (based on your earlier `podman info`, this is already correct).

---

### ✅ Recap of Where to Put These

```plaintext
~/.config/containers/policy.json         ← for trust policy (no signature enforcement)
~/.config/containers/containers.conf     ← for runtime default behavior
~/.config/containers/registries.conf     ← for registry resolution
```

---

Let me know if you want to:

* Add trusted keys and signatures later (e.g. with Cosign)
* Use declarative Nix/Home Manager to manage these configs
* Switch to a system-wide setup (`/etc/containers/`) instead of per-user
