### ISSUE TITLE
Add a k3s config file

### ISSUE THREAD

**Issue by sillypoise** [sillypoise/sp-dotfiles#2]
https://docs.k3s.io/installation/configuration#configuration-file

Yes — **absolutely worth a read**. That page covers the **`k3s` configuration file** format, which is super useful **if you want reproducibility, clarity, and integration with tools like Ansible or Nix** later.

Let me highlight what’s most relevant to your use case:

---

## ✅ Why Use a Config File for `k3s`?

* Keeps install options **declarative** and version-controlled.
* Avoids long, opaque `INSTALL_K3S_EXEC` strings in shell scripts.
* Great for automating your install with **Ansible** or tracking setup changes.
* Useful when you want to **add options like `--flannel-backend=none` or `--disable` components** (e.g., Traefik) and remember them.

---

## 📄 Example: Minimal Config File for Your Case

Create `/etc/rancher/k3s/config.yaml` (requires `sudo`):

```yaml
write-kubeconfig-mode: "0644"

# Don't install these automatically
disable:
  - traefik
  - servicelb
  - metrics-server
  - local-storage
  - network-policy  # <- disables network policy enforcement

# Optional: Custom cluster CIDR (if you're installing your own CNI later)
# cluster-cidr: 10.42.0.0/16
# service-cidr: 10.43.0.0/16
```

> You can also add `node-ip: <your-tailscale-ip>` if you want k3s to prefer using Tailscale for intra-node communication, which matters in multi-node setups.

Then install with:

```bash
curl -sfL https://get.k3s.io | sh -
```

No `INSTALL_K3S_EXEC` needed — the config file takes over.

---

## 🧠 Key Config Options You Might Want Later

| Option                          | What It Does                                                                   |
| ------------------------------- | ------------------------------------------------------------------------------ |
| `disable:`                      | Disables built-in services (like `traefik`) you want to manage yourself        |
| `flannel-backend: none`         | Disables built-in flannel, letting you install your own CNI                    |
| `tls-san:`                      | Useful for adding custom SANs (e.g., for Tailscale DNS) to the k3s server cert |
| `write-kubeconfig-mode: "0644"` | Makes the kubeconfig world-readable (useful in dev)                            |

---

## ✅ Recommended Action

Instead of installing with a long shell line, you can now do:

```bash
sudo mkdir -p /etc/rancher/k3s
sudo nano /etc/rancher/k3s/config.yaml
# paste config
curl -sfL https://get.k3s.io | sh -
```

Would you like me to generate an Ansible task block that sets this up declaratively?
